# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
    groups:
      npm:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'weekly'
    groups:
      npm:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/shared'
    schedule:
      interval: 'weekly'
    groups:
      npm:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/e2e'
    schedule:
      interval: 'weekly'
    groups:
      npm:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/docker/oidc-provider'
    schedule:
      interval: 'weekly'
    groups:
      npm:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
