FROM node:24.12.0-alpine

# Build argument for running in CI a bit more efficiently (without HMR)
ARG CI

# Install curl for health checks
RUN apk update && apk add curl

WORKDIR /app

COPY ./shared /app/shared

COPY ./backend /app/backend

COPY ./frontend /app/frontend

RUN cd /app/shared && npm install && npm run build

RUN cd /app/backend && npm install

RUN cd /app/frontend && \
  # Create the node_modules directory in advance to avoid runtime permission problems
  npm install && \
  chown -R node .

EXPOSE 8080

WORKDIR /app/frontend

# CI: Pre-build the bundle
RUN if [[ -n "$CI" ]]; then npm run build; fi

USER node

# CI: Run via preview, otherwise run via dev (with HMR)
CMD if [[ -n "$CI" ]]; then npm run preview; else npm run dev; fi
