services:
  oidc-provider:
    ports:
      - '127.0.0.1:9090:9090'

  sap-mock:
    build:
      context: ./docker/sap-mock/
      dockerfile: Dockerfile
    volumes:
      - ./docker/sap-mock:/app/
      - ./backend/resources/projectinfo.wsdl:/app/projectinfo.wsdl
      - ./backend/resources/actuals.wsdl:/app/actuals.wsdl
    ports:
      - '127.0.0.1:9043:3000'
    environment:
      - SAP_MOCK_PORT=3000

  db:
    image: postgis/postgis:12-3.3-alpine
    restart: always
    environment:
      POSTGRES_USER: app_user_dev
      POSTGRES_PASSWORD: DevPassword
      POSTGRES_DB: app_dev_db
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./docker/db/init/20-init.sql:/docker-entrypoint-initdb.d/20-init.sql
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: psql -U app_user_dev -d app_dev_db -c "SELECT 1"
      interval: 5s
      timeout: 5s
      retries: 10

  proxy:
    image: caddy:2-alpine
    ports:
      - '127.0.0.1:443:443'
    volumes:
      - ./docker/proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/proxy/data:/data
    environment:
      - PROXY_TARGET_HOST=host.docker.internal

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '127.0.0.1:8025:8025'
      - '127.0.0.1:1025:1025'

volumes:
  db-volume:
