/**
 * Options used to initialize (OpenLayers) Map -component
 */
export const mapOptions = {
  projection: {
    code: 'EPSG:3067',
    extent: [-548576, 6291456, 1548576, 8388608],
    units: 'm' as const,
    proj4String: '+proj=utm +zone=35 +ellps=GRS80 +units=m +no_defs',
  },
  baseMaps: [
    {
      id: 'opaskartta',
      title: 'Opaskartta',
      name: 'Opaskartta',
      visible: true,
      type: 'base',
      options: {
        protocol: 'wmts',
        url: 'https://georaster.tampere.fi/geoserver/gwc/service/wmts?service=WMTS',
        layer: 'georaster:opaskartta_EPSG_3067',
        matrixSet: 'JHS',
        projection: 'EPSG:3067',
        format: 'image/png',
        tileGridID: 'JHS',
        tileSize: 256,
        zoomLevels: 16,
        zoomFactor: 2,
      },
      opacity: 1.0,
      attributions: [],
    },
    {
      id: 'kantakartta',
      title: 'Kantakartta',
      name: 'Kantakartta',
      visible: true,
      type: 'base',
      options: {
        protocol: 'wmts',
        url: 'https://georaster.tampere.fi/geoserver/gwc/service/wmts?service=WMTS',
        layer: 'georaster:kantakartta_mml_harmaa_EPSG_3067',
        matrixSet: 'JHS',
        projection: 'EPSG:3067',
        format: 'image/png',
        tileGridID: 'JHS',
        tileSize: 256,
        zoomLevels: 16,
        zoomFactor: 2,
      },
      opacity: 1.0,
      attributions: [],
    },
    {
      id: 'ilmakuva',
      title: 'Ilmakuva',
      name: 'Ilmakuva',
      visible: true,
      type: 'base',
      options: {
        protocol: 'wmts',
        url: 'https://georaster.tampere.fi/geoserver/gwc/service/wmts?service=WMTS',
        layer: 'georaster:2011v_tre_EPSG_3067',
        matrixSet: 'JHS',
        projection: 'EPSG:3067',
        format: 'image/png',
        tileGridID: 'JHS',
        tileSize: 256,
        zoomLevels: 16,
        zoomFactor: 2,
      },
      opacity: 1.0,
      attributions: [],
    },
    {
      id: 'asemakaava',
      title: 'Asemakaava',
      name: 'Asemakaava',
      visible: true,
      type: 'base',
      options: {
        protocol: 'wmts',
        url: 'https://georaster.tampere.fi/geoserver/gwc/service/wmts?service=WMTS',
        layer: 'georaster:ajantasa_asemakaava_EPSG_3067',
        matrixSet: 'JHS',
        projection: 'EPSG:3067',
        format: 'image/png',
        tileGridID: 'JHS',
        tileSize: 256,
        zoomLevels: 16,
        zoomFactor: 2,
      },
      opacity: 1.0,
      attributions: [],
    },
  ],
};
