INSERT INTO app.code(id, text_fi, text_en)
VALUES
(('TehtävänElinkaarentila', '01'), 'Aloittamatta', 'Aloittamatta'),
(('TehtävänElinkaarentila', '02'), 'Käynnissä', 'Käynnissä'),
(('TehtävänElinkaarentila', '03'), 'Valmis', 'Valmis'),
(('TehtävänElinkaarentila', '04'), 'Odottaa', 'Odottaa');

INSERT INTO app.code(id, text_fi, text_en)
VALUES
(('TehtäväTyyppi', '2110'), 'Pohjatutkimus ja -mittaus', 'Pohjatutkimus ja -mittaus'),
(('TehtäväTyyppi', '2120'), 'Liikennetutkimus ja -mittaus', 'Liikennetutkimus ja -mittaus'),
(('TehtäväTyyppi', '2130'), 'Pima pohjatutkimus ja -mittaus', 'Pima pohjatutkimus ja -mittaus'),
(('TehtäväTyyppi', '2201'), 'Liikennesuunnittelu', 'Liikennesuunnittelu'),
(('TehtäväTyyppi', '2202'), 'Katu- ja katurakennesuunnittelu', 'Katu- ja katurakennesuunnittelu'),
(('TehtäväTyyppi', '2203'), 'Torien ja aukioiden suunnittelu', 'Torien ja aukioiden suunnittelu'),
(('TehtäväTyyppi', '2204'), 'Valaistussuunnittelu', 'Valaistussuunnittelu'),
(('TehtäväTyyppi', '2205'), 'Liikennetelematiikan suunnittelu', 'Liikennetelematiikan suunnittelu'),
(('TehtäväTyyppi', '2206'), 'Vesihuollon suunnittelu', 'Vesihuollon suunnittelu'),
(('TehtäväTyyppi', '2207'), 'Viher- ja ympäristösuunnittelu', 'Viher- ja ympäristösuunnittelu'),
(('TehtäväTyyppi', '2208'), 'Siltasuunnittelu', 'Siltasuunnittelu'),
(('TehtäväTyyppi', '2209'), 'Satamasuunnittelu', 'Satamasuunnittelu'),
(('TehtäväTyyppi', '2210'), 'Geosuunnittelu', 'Geosuunnittelu'),
(('TehtäväTyyppi', '2211'), 'Muu suunnittelu', 'Muu suunnittelu'),
(('TehtäväTyyppi', '2212'), 'Hakemussuunnittelu', 'Hakemussuunnittelu'),
(('TehtäväTyyppi', '2213'), 'Hulevesisuunnittelu', 'Hulevesisuunnittelu'),
(('TehtäväTyyppi', '2214'), 'Arkkitehtisuunnittelu', 'Arkkitehtisuunnittelu'),
(('TehtäväTyyppi', '2215'), 'Tietomallinnus', 'Tietomallinnus'),
(('TehtäväTyyppi', '2216'), 'Asiantuntija- ja kehityspalvelu', 'Asiantuntija- ja kehityspalvelu'),
(('TehtäväTyyppi', '2217'), 'Työmaapalvelu', 'Työmaapalvelu'),
(('TehtäväTyyppi', '3110'), 'Rakennuttamispalvelu', 'Rakennuttamispalvelu'),
(('TehtäväTyyppi', '3120'), 'Mittaus - ja tutkimuspalvelu', 'Mittaus - ja tutkimuspalvelu'),
(('TehtäväTyyppi', '3210'), 'Ajoradan rakentaminen', 'Ajoradan rakentaminen'),
(('TehtäväTyyppi', '3220'), 'Ajoradan ja kevyen liikenteen väylän rakentaminen', 'Ajoradan ja kevyen liikenteen väylän rakentaminen'),
(('TehtäväTyyppi', '3230'), 'Kevyen liikenteen väylän rakentaminen', 'Kevyen liikenteen väylän rakentaminen'),
(('TehtäväTyyppi', '3240'), 'Torin ja yleisen alueen rakentaminen', 'Torin ja yleisen alueen rakentaminen'),
(('TehtäväTyyppi', '3250'), 'Katuviheralueen rakentaminen', 'Katuviheralueen rakentaminen'),
(('TehtäväTyyppi', '3260'), 'Liikenteenohjaus', 'Liikenteenohjaus'),
(('TehtäväTyyppi', '3270'), 'Pilaantuneen maan siivoaminen', 'Pilaantuneen maan siivoaminen'),
(('TehtäväTyyppi', '3280'), 'Muu väylärakentaminen', 'Muu väylärakentaminen'),
(('TehtäväTyyppi', '3290'), 'Työnaikainen järjestely', 'Työnaikainen järjestely'),
(('TehtäväTyyppi', '3310'), 'Valaistuksen rakentaminen', 'Valaistuksen rakentaminen'),
(('TehtäväTyyppi', '3320'), 'Telematiikan rakentaminen', 'Telematiikan rakentaminen'),
(('TehtäväTyyppi', '3330'), 'Sulatusjärjestelmän rakentaminen', 'Sulatusjärjestelmän rakentaminen'),
(('TehtäväTyyppi', '3340'), 'Jätevesiviemärin rakentaminen', 'Jätevesiviemärin rakentaminen'),
(('TehtäväTyyppi', '3350'), 'Hulevesiviemärin rakentaminen', 'Hulevesiviemärin rakentaminen'),
(('TehtäväTyyppi', '3360'), 'Vesijohdon rakentaminen', 'Vesijohdon rakentaminen'),
(('TehtäväTyyppi', '3370'), 'Hulevesialtaan rakentaminen', 'Hulevesialtaan rakentaminen'),
(('TehtäväTyyppi', '3380'), 'Teletekniikan rakentaminen', 'Teletekniikan rakentaminen'),
(('TehtäväTyyppi', '3390'), 'Jätteen imukeräys', 'Jätteen imukeräys'),
(('TehtäväTyyppi', '3410'), 'Puiston rakentaminen', 'Puiston rakentaminen'),
(('TehtäväTyyppi', '3420'), 'Leikkipaikan rakentaminen', 'Leikkipaikan rakentaminen'),
(('TehtäväTyyppi', '3430'), 'Kentän rakentaminen', 'Kentän rakentaminen'),
(('TehtäväTyyppi', '3440'), 'Muu puistorakentaminen', 'Muu puistorakentaminen'),
(('TehtäväTyyppi', '3510'), 'Sillan rakentaminen', 'Sillan rakentaminen'),
(('TehtäväTyyppi', '3610'), 'Sataman rakentaminen', 'Sataman rakentaminen'),
(('TehtäväTyyppi', '3710'), 'Tukimuurin rakentaminen', 'Tukimuurin rakentaminen'),
(('TehtäväTyyppi', '3720'), 'Portaiden rakentaminen', 'Portaiden rakentaminen'),
(('TehtäväTyyppi', '3730'), 'Melusuojauksen rakentaminen', 'Melusuojauksen rakentaminen'),
(('TehtäväTyyppi', '3740'), 'Muu erikoisrakentaminen', 'Muu erikoisrakentaminen'),
(('TehtäväTyyppi', '4110'), 'Liikenneväylän talvihoito', 'Liikenneväylän talvihoito'),
(('TehtäväTyyppi', '4120'), 'Liikenneväylän kesähoito', 'Liikenneväylän kesähoito'),
(('TehtäväTyyppi', '4130'), 'Liikenneväylän kunnossapito', 'Liikenneväylän kunnossapito'),
(('TehtäväTyyppi', '4140'), 'Liikenneväylän päällystäminen', 'Liikenneväylän päällystäminen'),
(('TehtäväTyyppi', '4150'), 'Radan kunnossapito', 'Radan kunnossapito'),
(('TehtäväTyyppi', '4160'), 'Liikenneväylän muu lisätyö', 'Liikenneväylän muu lisätyö'),
(('TehtäväTyyppi', '4170'), 'Liikenneväylän ilkivaltavahingon hoito', 'Liikenneväylän ilkivaltavahingon hoito'),
(('TehtäväTyyppi', '4180'), 'Liikenneväylän ylläpidon kustannussuunnittelu', 'Liikenneväylän ylläpidon kustannussuunnittelu'),
(('TehtäväTyyppi', '4190'), 'Satamien kunnossapitosuunnittelu', 'Satamien kunnossapitosuunnittelu'),
(('TehtäväTyyppi', '4210'), 'Viheralueen nurmikoiden hoito', 'Viheralueen nurmikoiden hoito'),
(('TehtäväTyyppi', '4220'), 'Puiden pensaiden ja muun kasvillisuuden hoito', 'Puiden pensaiden ja muun kasvillisuuden hoito'),
(('TehtäväTyyppi', '4230'), 'Viheralueen kukkakasvien hoito', 'Viheralueen kukkakasvien hoito'),
(('TehtäväTyyppi', '4240'), 'Leikki- ja liikuntapaikkojen kunnossapito', 'Leikki- ja liikuntapaikkojen kunnossapito'),
(('TehtäväTyyppi', '4260'), 'Viheralueen kalusteiden kunnossapito', 'Viheralueen kalusteiden kunnossapito'),
(('TehtäväTyyppi', '4270'), 'Viheralueen muu kunnossapito', 'Viheralueen muu kunnossapito'),
(('TehtäväTyyppi', '4290'), 'Viheralueen muu lisätyö', 'Viheralueen muu lisätyö'),
(('TehtäväTyyppi', '4310'), 'Liikenteenohjauslaitteen ylläpito', 'Liikenteenohjauslaitteen ylläpito'),
(('TehtäväTyyppi', '4320'), 'Kuivatusjärjestelmän ylläpito', 'Kuivatusjärjestelmän ylläpito'),
(('TehtäväTyyppi', '4330'), 'Sulatusjärjestelmän ylläpito', 'Sulatusjärjestelmän ylläpito'),
(('TehtäväTyyppi', '4340'), 'Sillan ja rakenteen kunnossapito', 'Sillan ja rakenteen kunnossapito'),
(('TehtäväTyyppi', '4350'), 'Kalusteen kunnossapito', 'Kalusteen kunnossapito'),
(('TehtäväTyyppi', '4360'), 'Varusteiden, laitteiden ja rakenteiden energia', 'Varusteiden, laitteiden ja rakenteiden energia'),
(('TehtäväTyyppi', '4410'), 'Liikennetelematiikan energia', 'Liikennetelematiikan energia'),
(('TehtäväTyyppi', '4420'), 'Liikennetelematiikan kunnossapito', 'Liikennetelematiikan kunnossapito'),
(('TehtäväTyyppi', '4430'), 'Liikennetelematiikan tietoliikenne', 'Liikennetelematiikan tietoliikenne'),
(('TehtäväTyyppi', '4510'), 'Ulkovalaistuksen energia', 'Ulkovalaistuksen energia'),
(('TehtäväTyyppi', '4520'), 'Ulkovalaistuksen kunnossapito', 'Ulkovalaistuksen kunnossapito'),
(('TehtäväTyyppi', '4530'), 'Ulkovalaistuksen ohjaus', 'Ulkovalaistuksen ohjaus'),
(('TehtäväTyyppi', '4540'), 'Ulkovalaistuksen dokumentointi', 'Ulkovalaistuksen dokumentointi'),
(('TehtäväTyyppi', '4550'), 'Ulkovalaistuksen käyttötehtävä', 'Ulkovalaistuksen käyttötehtävä'),
(('TehtäväTyyppi', '4560'), 'Ulkovalaistuksen takuutarkastus', 'Ulkovalaistuksen takuutarkastus'),
(('TehtäväTyyppi', '4610'), 'Katujen ja alueiden puhtaanapito', 'Katujen ja alueiden puhtaanapito'),
(('TehtäväTyyppi', '4620'), 'Viheralueiden puhtaanapito', 'Viheralueiden puhtaanapito'),
(('TehtäväTyyppi', '4630'), 'Puhdistustyö', 'Puhdistustyö'),
(('TehtäväTyyppi', '4810'), 'Syöksykaivon tyhjennys', 'Syöksykaivon tyhjennys'),
(('TehtäväTyyppi', '4820'), 'Sulatus', 'Sulatus'),
(('TehtäväTyyppi', '4830'), 'Ojanperkaus', 'Ojanperkaus'),
(('TehtäväTyyppi', '4840'), 'Hulevesipäivystys', 'Hulevesipäivystys'),
(('TehtäväTyyppi', '4850'), 'Huleveden asiakaspalvelu', 'Huleveden asiakaspalvelu'),
(('TehtäväTyyppi', '4860'), 'Huleveden asiantuntijapalvelu', 'Huleveden asiantuntijapalvelu');